"""Container-side execution wrapper for one-shot calls.

The generated script runs on the image's **Python 3.10**, so it deliberately
avoids 3.11+ syntax and APIs. The AST split happens here on the host; the
container only executes the emitted source (design note 14, §3.9).

`build_runner_source` reproduces Jupyter's `execute_result` semantics: if the
last top-level statement is an expression, its value is printed with `repr()`
unless it is `None`.
"""

from __future__ import annotations

import ast
from typing import Optional

RUNNER_PATH_IN_CONTAINER = "/runner/run.py"
RUNNER_PATH_IN_CALL = "control/run.py"
OUT_DIR_NAME = "out"
LOGS_DIR_NAME = "logs"


def _line_offsets(source: str) -> list[int]:
    offsets = [0]
    for line in source.splitlines(keepends=True):
        offsets.append(offsets[-1] + len(line))
    return offsets


def split_last_expression(source: str) -> tuple[str, Optional[str]]:
    """Split ``source`` into (head, last_expression_source).

    Returns ``(source, None)`` when the last top-level statement is not an
    expression, when the source is empty, or when the head would not compile on
    its own (for example a statement continued by the same line). Offsets come
    from the AST, so both multi-line expressions and ``a = 1; a`` work.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return source, None
    if not tree.body:
        return source, None
    last = tree.body[-1]
    if not isinstance(last, ast.Expr):
        return source, None

    offsets = _line_offsets(source)
    start = offsets[last.lineno - 1] + last.col_offset
    end = offsets[last.end_lineno - 1] + last.end_col_offset
    head, expression = source[:start], source[start:end]
    if not expression.strip():
        return source, None
    try:
        compile(head, "<head>", "exec")
    except SyntaxError:
        return source, None
    return head, expression


# Plain string (no formatting is applied) so braces stay literal.
_RUNNER_BODY = '''\
import sys
import traceback


def _prepare_matplotlib():
    try:
        import matplotlib
    except Exception:
        return
    try:
        matplotlib.use("Agg")
    except Exception:
        pass


def main():
    _prepare_matplotlib()
    namespace = {"__name__": "__main__", "__file__": "<tool>"}
    try:
        exec(compile(_USER_HEAD, "<tool>", "exec"), namespace)
        if _LAST_EXPRESSION is not None:
            value = eval(compile(_LAST_EXPRESSION, "<tool>", "eval"), namespace)
            if value is not None:
                print(repr(value))
    except SystemExit as exc:
        sys.stdout.flush()
        sys.stderr.flush()
        code = exc.code if isinstance(exc.code, int) else 1
        raise SystemExit(code)
    except BaseException:
        traceback.print_exc()
        sys.stdout.flush()
        sys.stderr.flush()
        raise SystemExit(1)
    sys.stdout.flush()
    sys.stderr.flush()


if __name__ == "__main__":
    main()
'''


def build_runner_source(source: str) -> str:
    """Emit the container-side runner script for one call."""
    head, expression = split_last_expression(source)
    return "\n".join(
        [
            "# Generated by sandbox.exec_wrapper; must run on the image's Python 3.10.",
            "_USER_HEAD = " + repr(head),
            "_LAST_EXPRESSION = " + repr(expression),
            "",
            _RUNNER_BODY,
        ]
    )
